### ISSUE TITLE
nanoGPT 기반으로, A100 사용하여 pretrain 시, A100의 vram은 80GB였나요?

### ISSUE THREAD

**Issue by ethany21** [yoonhero/jamo_llm#1]
우선 좋은 연구 감사드립니다.

pretrain 시에 사용했던 A100 모델의 vram은 80GB 였나요?

google colab pro + 기준 A100 모델은 vram이 40GB 였기에 질문 드립니다.

또한 단일 A100만 사용했는지 여러 대를 병렬 연결하여 pretrain 한 것인지도 알고 싶습니다.

**Comment by yoonhero** [comment]
저희 연구팀은 VRAM 40GB 하나의 A100 그래픽카드로 사전 학습을 진행했습니다. 단일 A100을 활용하였지만 여건이 되신다면 여러 대를 클러스터로 구성하여 분산 학습을 진행한다면 더 빠르게 학습을 진행하실 수 있을 것 같습니다.
