### ISSUE TITLE
full fine tune이 아닌 lora 방식으로 파인 튜닝하는 cli 예제가 있을까요?

### ISSUE THREAD

**Issue by ethany21** [yoonhero/jamo_llm#2]
현재 단일 4090 rtx 사용 중인데, PEFT방식으로 적은 데이터셋으로 일부 파라미터만 파인 튜닝 하려고 한다면

지원하는 cli 예제가 있을 지 알고 싶습니다.

**Comment by yoonhero** [comment]
제가 공개한 모델 가중치를 파인 튜닝하신다면 PEFT 방식이 아니더라도 충분히 진행하실 수 있을 것입니다. 저희 연구팀이 테스트를 해본 결과 맥북 프로 CPU로도 충분히 파인튜닝을 돌릴 수 있는 것을 확인할 수 있습니다. 한 번 하이퍼파라메터를 튜닝하시면서 테스트하면 될 것 같습니다.
